shell:
  program: /usr/bin/tmux
  args:
    - new
    - -A
    - -s main

env:
  TERM: alacritty

window:
  dimensions:
    columns: 150
    lines: 40
  opacity: 0.98
  padding:
    x: 8
    y: 4

scrolling:
  history: 99999

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Medium
  italic:
    family: JetBrains Mono
    style: Italic
  size: 16.0
  offset:
    x: 3
    y: 2
  glyph_offset:
    x: 0
    y: 0

selection:
  save_to_clipboard: true

cursor:
  style: Beam

# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#eaeaea'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e6c547'
    blue:    '#7aa6da'
    magenta: '#c397d8'
    cyan:    '#70c0ba'
    white:   '#424242'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#2a2a2a'
